#!/usr/bin/env python3
"""Subset the full Google-Fonts TTFs (downloaded to tmp/kit/ttf) into compact local woff2.

Character set = ASCII + Latin-1 + Latin Ext-A + typographic punctuation/symbols
              + CJK punctuation, full-width forms, Bopomofo
              + Big5 symbols (A140-A3BF) + Big5 level-1 "常用字" (A440-C67E, 5401 chars)
              + every character found in SPEC.md, facts/facts.json, comp/**/*.{html,js,json}
              + EXTRA (below).
Re-run any time new on-screen text is added:  python3 assets/kit/tools/build_fonts.py
Download step (only if tmp/kit/ttf is missing):  python3 assets/kit/tools/build_fonts.py --download
"""
import glob, os, sys, subprocess, json, re
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
KIT = os.path.join(ROOT, 'assets', 'kit')
TTF = os.path.join(ROOT, 'tmp', 'kit', 'ttf')
OUT = os.path.join(KIT, 'fonts')

FACES = [  # (file stem, css family, weight, subset?)
    ('NotoSansTC-900',   'Noto Sans TC',     900, 'Noto+Sans+TC:wght@900',   True),
    ('NotoSansTC-700',   'Noto Sans TC',     700, 'Noto+Sans+TC:wght@700',   True),
    ('NotoSansTC-500',   'Noto Sans TC',     500, 'Noto+Sans+TC:wght@500',   True),
    ('NotoSerifTC-900',  'Noto Serif TC',    900, 'Noto+Serif+TC:wght@900',  True),
    ('LXGWWenKaiTC-400', 'LXGW WenKai TC',   400, 'LXGW+WenKai+TC:wght@400', True),
    ('LXGWWenKaiTC-700', 'LXGW WenKai TC',   700, 'LXGW+WenKai+TC:wght@700', True),
    ('Anton-400',        'Anton',            400, 'Anton',                   False),
    ('SpaceMono-700',    'Space Mono',       700, 'Space+Mono:wght@700',     False),
    ('SpaceMono-400',    'Space Mono',       400, 'Space+Mono:wght@400',     False),
    ('PermanentMarker-400', 'Permanent Marker', 400, 'Permanent+Marker',     False),
]

EXTRA = ("台灣人有多少那麼在挪威的稀有度遇到歡迎來到下一站出發首都奧斯陸人口約萬面積個大峽灣世界遺產"
         "貨幣克朗語言冬季極光夏季午夜太陽平均每位居民才秒認識一國家估計資料來源統計局你可能就是其中之"
         "臺灣挪威王國北歐斯堪地那維亞峽灣極圈羅弗敦特羅姆瑟卑爾根蓋倫格盧斯峽灣聖壇岩維京鮭魚"
         "旅外僑胞僑委會外交部內政部移民署駐瑞典代表處登機證護照航班座位登機門出發抵達乘客"
         "約≈×÷±°²³★☆✦✧✈→←↑↓↗↘⇢•·…‥—–‐‑‒―‘’“”„‚‹›«»「」『』（）【】〔〕《》〈〉、。，．：；？！～"
         "①②③④⑤⑥⑦⑧⑨⑩●○◎◉■□▲△▼▽◆◇♥♡✓✔✕✖✗✘№€£¥$¢%‰#@&*＋－＝／＼｜＿")

def charset():
    cps = set(range(0x20, 0x7F)) | set(range(0xA0, 0x180)) | set(range(0x2000, 0x2070))
    cps |= set(range(0x2190, 0x21A0)) | {0x2116, 0x2122, 0x2160, 0x2161, 0x2162, 0x2163}
    cps |= set(range(0x3000, 0x3040)) | set(range(0xFF01, 0xFF66)) | set(range(0xFFE0, 0xFFE7))
    cps |= set(range(0x3105, 0x312A)) | set(range(0x02C6, 0x02DE))   # bopomofo + tone marks
    cps |= set(range(0x2460, 0x2474)) | set(range(0x25A0, 0x25FF)) | set(range(0x2600, 0x2610))
    cps |= {0x2713, 0x2714, 0x2715, 0x2716, 0x2717, 0x2718, 0x2726, 0x2727, 0x2708, 0x2764}
    def big5(lo_hi, trail_ranges):
        out = set()
        for lead in range(lo_hi[0], lo_hi[1] + 1):
            for a, b in trail_ranges:
                for t in range(a, b + 1):
                    try: out.add(ord(bytes([lead, t]).decode('big5')))
                    except Exception: pass
        return out
    trails = [(0x40, 0x7E), (0xA1, 0xFE)]
    cps |= big5((0xA1, 0xA3), trails)      # symbols & punctuation
    cps |= big5((0xA4, 0xC6), trails)      # level-1 frequently used hanzi (5401)
    texts = [EXTRA]
    for pat in ['SPEC.md', 'facts/*.json', 'comp/**/*.html', 'comp/**/*.js', 'comp/**/*.json',
                'assets/kit/*.html', 'assets/kit/*.js', 'assets/kit/svg/*.svg', 'assets/kit/svg/*.js']:
        for f in glob.glob(os.path.join(ROOT, pat), recursive=True):
            try: texts.append(open(f, encoding='utf-8').read())
            except Exception: pass
    for t in texts:
        for ch in t:
            o = ord(ch)
            if o >= 0x2E80 or 0x2000 <= o < 0x2E80 or 0x20 <= o < 0x250: cps.add(o)
    return sorted(c for c in cps if c not in (0xFEFF,))

def download():
    import urllib.request
    os.makedirs(TTF, exist_ok=True)
    for stem, fam, w, q, _ in FACES:
        dst = os.path.join(TTF, stem + '.ttf')
        if os.path.exists(dst): continue
        css = urllib.request.urlopen('https://fonts.googleapis.com/css2?family=' + q).read().decode()
        url = re.search(r'url\((https://[^)]+\.ttf)\)', css).group(1)
        print('download', stem, url); urllib.request.urlretrieve(url, dst)

def main():
    if '--download' in sys.argv or not os.path.isdir(TTF): download()
    cps = charset()
    os.makedirs(OUT, exist_ok=True)
    txt = ''.join(chr(c) for c in cps)
    open(os.path.join(OUT, 'charset.txt'), 'w', encoding='utf-8').write(txt)
    ucodes = os.path.join(OUT, '.unicodes.txt')
    open(ucodes, 'w').write('\n'.join('U+%04X' % c for c in cps))
    css = ['/* Local font kit (SIL Open Font License 1.1, see fonts/OFL.txt). Generated by tools/build_fonts.py */']
    for stem, fam, w, q, sub in FACES:
        src = os.path.join(TTF, stem + '.ttf'); dst = os.path.join(OUT, stem + '.woff2')
        args = ['pyftsubset', src, '--flavor=woff2', '--output-file=' + dst,
                '--layout-features=*', '--name-IDs=*', '--notdef-outline', '--no-hinting', '--desubroutinize']
        args += (['--unicodes-file=' + ucodes] if sub else ['--unicodes=*'])
        subprocess.run(args, check=True)
        print('%-22s %8.1f KB' % (stem, os.path.getsize(dst) / 1024))
        css.append("@font-face{font-family:'%s';font-style:normal;font-weight:%d;font-display:block;"
                   "src:url('%s.woff2') format('woff2');}" % (fam, w, stem))
    # convenience aliases (single-weight families, easier to use in canvas ctx.font)
    alias = [('Noto Sans TC Black', 'NotoSansTC-900'), ('Noto Sans TC Bold', 'NotoSansTC-700'),
             ('Noto Serif TC Black', 'NotoSerifTC-900'), ('WenKai', 'LXGWWenKaiTC-700')]
    for a, stem in alias:
        css.append("@font-face{font-family:'%s';font-style:normal;font-weight:100 1000;font-display:block;"
                   "src:url('%s.woff2') format('woff2');}" % (a, stem))
    open(os.path.join(OUT, 'fonts.css'), 'w').write('\n'.join(css) + '\n')
    os.remove(ucodes)
    print(len(cps), 'code points')

if __name__ == '__main__':
    main()
